### ISSUE TITLE
Not possible to override foundation variables

### ISSUE THREAD

**Issue by simonjcarr** [m66n/vue-fdn#1]
Everything is working fine out of the box, but I am not able to override any of the foundation variables from within a component. The only way to change the style is to do it in the _settings.scss file.

Am I missing something?

**Comment by m66n** [comment]
When `@import 'foundation';` is processed by node-sass all the variables that Foundation uses must be defined. Redefining them after the fact will not have any effect. So the only place to change them is in `_settings.scss` or before `@import 'foundation';` in `style.scss`. Otherwise you'd have to use a CSS selector in your component and override the default.
